ALTER TABLE `user`
-- salt gets generated by the BcryptEncoder, so it's not neccessary anymore
DROP COLUMN `password_salt`,
CHANGE COLUMN `password_hash` `password_hash` VARCHAR(60) NULL DEFAULT NULL ;
