CREATE TABLE `store` ( `id` INT NOT NULL AUTO_INCREMENT , `type_id` INT NOT NULL , `name` VARCHAR(255) NOT NULL , `address` VARCHAR(500) NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `store` ADD FOREIGN KEY (`type_id`) REFERENCES `store_type`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
