CREATE TABLE `item_history` ( `id` INT NOT NULL AUTO_INCREMENT , `item_id` INT NOT NULL , `type` VARCHAR(20) NOT NULL ,`user_id` INT NULL, `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `data` VARCHAR(1000) NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `item_history` ADD FOREIGN KEY (`item_id`) REFERENCES `item`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `item_history` ADD FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
