language: java
jdk: oraclejdk11
addons:
  sonarcloud:
    organization: "janneskretschmer-github" # the key of the org you chose at step #3
script:
  # other script steps might be done before running the actual analysis
  - mvn verify
  - sonar-scanner
deploy:
  - provider: script
    script: bash scripts/deploy.sh stage
    on:
      branch: stage
    skip_cleanup: true
  - provider: script
    script: bash scripts/deploy.sh prod
    on:
      branch: production
    skip_cleanup: true