version: '3'
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: lhtool
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: "lh-tool"
            MYSQL_PASSWORD: "lh-tool"
    tomcat:
        container_name: tomcat
        depends_on:
            - db
        image: "lhtool:0.0.1-SNAPSHOT"
        restart: always
        ports:
            - 8080:8080
        environment:
            WAIT_HOSTS: db:3306
        
