// Needs to be kept in sync with ExceptionEnum.java
export const EX_ILLEGAL_ID = 'EX_ILLEGAL_ID';
export const EX_FORBIDDEN = 'EX_FORBIDDEN';

export const EX_INVALID_ID = 'EX_INVALID_ID';
export const EX_INVALID_USER_ID = 'EX_INVALID_USER_ID';
export const EX_INVALID_PROJECT_ID = 'EX_INVALID_PROJECT_ID';
export const EX_INVALID_HELPER_TYPE_ID = 'EX_INVALID_HELPER_TYPE_ID';
export const EX_INVALID_STORE_ID = 'EX_INVALID_STORE_ID';
export const EX_INVALID_SLOT_ID = 'EX_INVALID_SLOT_ID';
export const EX_INVALID_ITEM_ID = 'EX_INVALID_ITEM_ID';
export const EX_INVALID_NOTE_ID = 'EX_INVALID_NOTE_ID';
export const EX_INVALID_TECHNICAL_CREW_ID = 'EX_INVALID_TECHNICAL_CREW_ID';

export const EX_NO_BROKEN = 'EX_NO_BROKEN';
export const EX_NO_CONSUMABLE = 'EX_NO_CONSUMABLE';
export const EX_NO_DATE = 'EX_NO_DATE';
export const EX_NO_EMAIL = 'EX_NO_EMAIL';
export const EX_NO_END_DATE = 'EX_NO_END_DATE';
export const EX_NO_END_TIME = 'EX_NO_END_TIME';
export const EX_NO_FIRST_NAME = 'EX_NO_FIRST_NAME';
export const EX_NO_GENDER = 'EX_NO_GENDER';
export const EX_NO_HAS_BARCODE = 'EX_NO_HAS_BARCODE';
export const EX_NO_HELPER_TYPE_ID = 'EX_NO_HELPER_TYPE_ID';
export const EX_NO_ID = 'EX_NO_ID';
export const EX_NO_IDENTIFIER = 'EX_NO_IDENTIFIER';
export const EX_NO_IMAGE = 'EX_NO_IMAGE';
export const EX_NO_ITEM_ID = 'EX_NO_ITEM_ID';
export const EX_NO_LAST_NAME = 'EX_NO_LAST_NAME';
export const EX_NO_MEDIA_TYPE = 'EX_NO_MEDIA_TYPE';
export const EX_NO_NAME = 'EX_NO_NAME';
export const EX_NO_NEED_ID = 'EX_NO_NEED_ID';
export const EX_NO_NOTE = 'EX_NO_NOTE';
export const EX_NO_OUTSIDE_QUALIFIED = 'EX_NO_OUTSIDE_QUALIFIED';
export const EX_NO_OUTSIDE = 'EX_NO_OUTSIDE';
export const EX_NO_PROJECT_ID = 'EX_NO_PROJECT_ID';
export const EX_NO_PROJECT_HELPER_TYPE_ID = 'EX_NO_PROJECT_HELPER_TYPE_ID';
export const EX_NO_QUANTITY = 'EX_NO_QUANTITY';
export const EX_NO_ROLE = 'EX_NO_ROLE';
export const EX_NO_SLOT_ID = 'EX_NO_SLOT_ID';
export const EX_NO_STORE_ID = 'EX_NO_STORE_ID';
export const EX_NO_START_DATE = 'EX_NO_START_DATE';
export const EX_NO_START_TIME = 'EX_NO_START_TIME';
export const EX_NO_STATE = 'EX_NO_STATE';
export const EX_NO_ITEM_TAG_ID = 'EX_NO_ITEM_TAG_ID';
export const EX_NO_TECHNICAL_CREW_ID = 'EX_NO_TECHNICAL_CREW_ID';
export const EX_NO_TIMESTAMP = 'EX_NO_TIMESTAMP';
export const EX_NO_TYPE = 'EX_NO_TYPE';
export const EX_NO_UNIT = 'EX_NO_UNIT';
export const EX_NO_USER_ID = 'EX_NO_USER_ID';
export const EX_NO_WEEKDAY = 'EX_NO_WEEKDAY';

export const EX_USER_EMAIL_ALREADY_IN_USE = 'EX_USER_EMAIL_ALREADY_IN_USE';
export const EX_USER_ROLE_ALREADY_EXISTS = 'EX_USER_ROLE_ALREADY_EXISTS';
export const EX_USER_SUICIDE = 'EX_USER_SUICIDE';

export const EX_PASSWORDS_DO_NOT_MATCH = 'EX_PASSWORDS_DO_NOT_MATCH';
export const EX_PASSWORDS_NO_TOKEN_OR_OLD_PASSWORD = 'EX_PASSWORDS_NO_TOKEN_OR_OLD_PASSWORD';
export const EX_PASSWORDS_INVALID_TOKEN = 'EX_PASSWORDS_INVALID_TOKEN';
export const EX_PASSWORDS_EXPIRED_TOKEN = 'EX_PASSWORDS_EXPIRED_TOKEN';
export const EX_PASSWORDS_INVALID_PASSWORD = 'EX_PASSWORDS_INVALID_PASSWORD';
export const EX_PASSWORDS_SHORT_PASSWORD = 'EX_PASSWORDS_SHORT_PASSWORD';

export const EX_PROJECT_NAME_ALREADY_EXISTS = 'EX_PROJECT_NAME_ALREADY_EXISTS';

export const EX_NEED_ALREADY_EXISTS = 'EX_NEED_ALREADY_EXISTS';
export const EX_NEED_USER_INVALID_STATE = 'EX_NEED_USER_INVALID_STATE';

export const EX_HELPER_TYPE_ALREADY_EXISTS = 'EX_HELPER_TYPE_ALREADY_EXISTS';
export const EX_HELPER_TYPE_WEEKDAY_WITHOUT_PROJECT = 'EX_HELPER_TYPE_WEEKDAY_WITHOUT_PROJECT';

export const EX_ITEM_ITEM_TAG_ALREADY_EXISTS = 'EX_ITEM_ITEM_TAG_ALREADY_EXISTS';
export const EX_ITEM_IDENTIFIER_ALREADY_IN_USE = 'EX_ITEM_IDENTIFIER_ALREADY_IN_USE';
export const EX_ITEM_SELF_RELATION = 'EX_ITEM_SELF_RELATION';
export const EX_ITEM_RELATION_ALREADY_EXISTS = 'EX_ITEM_RELATION_ALREADY_EXISTS';

export const EX_STORE_NOT_EMPTY = 'EX_STORE_NOT_EMPTY';

export const EX_SLOT_NOT_EMPTY = 'EX_SLOT_NOT_EMPTY';



