/////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                             //
//   ██████╗__██████╗_███╗___██╗_█╗_████████╗____████████╗_██████╗_██╗___██╗_██████╗██╗__██╗   //
//   ██╔══██╗██╔═══██╗████╗__██║_╚╝_╚══██╔══╝____╚══██╔══╝██╔═══██╗██║___██║██╔════╝██║__██║   //
//   ██║__██║██║___██║██╔██╗_██║_______██║__________██║___██║___██║██║___██║██║_____███████║   //
//   ██║__██║██║___██║██║╚██╗██║_______██║__________██║___██║___██║██║___██║██║_____██╔══██║   //
//   ██████╔╝╚██████╔╝██║_╚████║_______██║__________██║___╚██████╔╝╚██████╔╝╚██████╗██║__██║   //
//   ╚═════╝__╚═════╝_╚═╝__╚═══╝_______╚═╝__________╚═╝____╚═════╝__╚═════╝__╚═════╝╚═╝__╚═╝   //
//                                                                                             //
/////////////////////////////////////////////////////////////////////////////////////////////////

// This file got generated from UserRole.java

export const ROLE_ADMIN = 'ROLE_ADMIN';
export const ROLE_CONSTRUCTION_SERVANT = 'ROLE_CONSTRUCTION_SERVANT';
export const ROLE_LOCAL_COORDINATOR = 'ROLE_LOCAL_COORDINATOR';
export const ROLE_ATTENDANCE = 'ROLE_ATTENDANCE';
export const ROLE_PUBLISHER = 'ROLE_PUBLISHER';
export const ROLE_STORE_KEEPER = 'ROLE_STORE_KEEPER';
export const ROLE_INVENTORY_MANAGER = 'ROLE_INVENTORY_MANAGER';
export const GET_SUFFIX = '_GET';
export const POST_SUFFIX = '_POST';
export const PUT_SUFFIX = '_PUT';
export const DELETE_SUFFIX = '_DELETE';
export const CHANGE_FOREIGN_SUFFIX = '_CHANGE_FOREIGN';
export const USERS_PREFIX = 'ROLE_RIGHT_USERS';
export const RIGHT_USERS_GET = 'ROLE_RIGHT_USERS_GET';
export const RIGHT_USERS_POST = 'ROLE_RIGHT_USERS_POST';
export const RIGHT_USERS_PUT = 'ROLE_RIGHT_USERS_PUT';
export const RIGHT_USERS_DELETE = 'ROLE_RIGHT_USERS_DELETE';
export const RIGHT_USERS_CHANGE_FOREIGN = 'ROLE_RIGHT_USERS_CHANGE_FOREIGN';
export const RIGHT_USERS_CHANGE_FOREIGN_PASSWORD = 'ROLE_RIGHT_USERS_CHANGE_FOREIGN_PASSWORD';
export const USERS_ROLES_PREFIX = 'ROLE_RIGHT_USERS_ROLES';
export const RIGHT_USERS_ROLES_GET = 'ROLE_RIGHT_USERS_ROLES_GET';
export const RIGHT_USERS_ROLES_GET_FOREIGN = 'ROLE_RIGHT_USERS_ROLES_GET_FOREIGN';
export const RIGHT_USERS_ROLES_POST = 'ROLE_RIGHT_USERS_ROLES_POST';
export const RIGHT_USERS_ROLES_DELETE = 'ROLE_RIGHT_USERS_ROLES_DELETE';
export const USERS_GRANT_ROLE_PREFIX = 'ROLE_RIGHT_USERS_GRANT';
export const RIGHT_USERS_GRANT_ROLE_ADMIN = 'ROLE_RIGHT_USERS_GRANT_ROLE_ADMIN';
export const RIGHT_USERS_GRANT_ROLE_CONSTRUCTION_SERVANT = 'ROLE_RIGHT_USERS_GRANT_ROLE_CONSTRUCTION_SERVANT';
export const RIGHT_USERS_GRANT_ROLE_LOCAL_COORDINATOR = 'ROLE_RIGHT_USERS_GRANT_ROLE_LOCAL_COORDINATOR';
export const RIGHT_USERS_GRANT_ROLE_ATTENDANCE = 'ROLE_RIGHT_USERS_GRANT_ROLE_ATTENDANCE';
export const RIGHT_USERS_GRANT_ROLE_PUBLISHER = 'ROLE_RIGHT_USERS_GRANT_ROLE_PUBLISHER';
export const RIGHT_USERS_GRANT_ROLE_STORE_KEEPER = 'ROLE_RIGHT_USERS_GRANT_ROLE_STORE_KEEPER';
export const RIGHT_USERS_GRANT_ROLE_INVENTORY_MANAGER = 'ROLE_RIGHT_USERS_GRANT_ROLE_INVENTORY_MANAGER';
export const PROJECTS_PREFIX = 'ROLE_RIGHT_PROJECTS';
export const RIGHT_PROJECTS_GET = 'ROLE_RIGHT_PROJECTS_GET';
export const RIGHT_PROJECTS_POST = 'ROLE_RIGHT_PROJECTS_POST';
export const RIGHT_PROJECTS_PUT = 'ROLE_RIGHT_PROJECTS_PUT';
export const RIGHT_PROJECTS_DELETE = 'ROLE_RIGHT_PROJECTS_DELETE';
export const RIGHT_PROJECTS_CHANGE_FOREIGN = 'ROLE_RIGHT_PROJECTS_CHANGE_FOREIGN';
export const PROJECTS_USERS_PREFIX = 'ROLE_RIGHT_PROJECTS_USERS';
export const RIGHT_PROJECTS_USERS_GET = 'ROLE_RIGHT_PROJECTS_USERS_GET';
export const RIGHT_PROJECTS_USERS_POST = 'ROLE_RIGHT_PROJECTS_USERS_POST';
export const RIGHT_PROJECTS_USERS_DELETE = 'ROLE_RIGHT_PROJECTS_USERS_DELETE';
export const RIGHT_PROJECTS_USERS_CHANGE_FOREIGN = 'ROLE_RIGHT_PROJECTS_USERS_CHANGE_FOREIGN';
export const PROJECTS_HELPER_TYPES_PREFIX = 'ROLE_RIGHT_PROJECTS_HELPER_TYPES';
export const RIGHT_PROJECTS_HELPER_TYPES_GET = 'ROLE_RIGHT_PROJECTS_HELPER_TYPES_GET';
export const RIGHT_PROJECTS_HELPER_TYPES_POST = 'ROLE_RIGHT_PROJECTS_HELPER_TYPES_POST';
export const RIGHT_PROJECTS_HELPER_TYPES_PUT = 'ROLE_RIGHT_PROJECTS_HELPER_TYPES_PUT';
export const RIGHT_PROJECTS_HELPER_TYPES_DELETE = 'ROLE_RIGHT_PROJECTS_HELPER_TYPES_DELETE';
export const HELPER_TYPES_PREFIX = 'ROLE_RIGHT_HELPER_TYPES';
export const RIGHT_HELPER_TYPES_GET = 'ROLE_RIGHT_HELPER_TYPES_GET';
export const RIGHT_HELPER_TYPES_POST = 'ROLE_RIGHT_HELPER_TYPES_POST';
export const RIGHT_HELPER_TYPES_PUT = 'ROLE_RIGHT_HELPER_TYPES_PUT';
export const RIGHT_HELPER_TYPES_DELETE = 'ROLE_RIGHT_HELPER_TYPES_DELETE';
export const NEEDS_PREFIX = 'ROLE_RIGHT_NEEDS';
export const RIGHT_NEEDS_GET = 'ROLE_RIGHT_NEEDS_GET';
export const RIGHT_NEEDS_POST = 'ROLE_RIGHT_NEEDS_POST';
export const RIGHT_NEEDS_PUT = 'ROLE_RIGHT_NEEDS_PUT';
export const RIGHT_NEEDS_DELETE = 'ROLE_RIGHT_NEEDS_DELETE';
export const RIGHT_NEEDS_CHANGE_FOREIGN_PROJECT = 'ROLE_RIGHT_NEEDS_CHANGE_FOREIGN_PROJECT';
export const RIGHT_NEEDS_CHANGE_FOREIGN_USER = 'ROLE_RIGHT_NEEDS_CHANGE_FOREIGN_USER';
export const RIGHT_NEEDS_GET_FOREIGN_USER = 'ROLE_RIGHT_NEEDS_GET_FOREIGN_USER';
export const RIGHT_NEEDS_GET_ANONYMIZED_USER_LIST = 'ROLE_RIGHT_NEEDS_GET_ANONYMIZED_USER_LIST';
export const RIGHT_NEEDS_APPLY = 'ROLE_RIGHT_NEEDS_APPLY';
export const RIGHT_NEEDS_APPROVE = 'ROLE_RIGHT_NEEDS_APPROVE';
export const RIGHT_NEEDS_VIEW_APPROVED = 'ROLE_RIGHT_NEEDS_VIEW_APPROVED';
export const NEEDS_USERS_PREFIX = 'ROLE_RIGHT_NEEDS_USERS';
export const RIGHT_NEEDS_USERS_PUT = 'ROLE_RIGHT_NEEDS_USERS_PUT';
export const RIGHT_NEEDS_USERS_GET = 'ROLE_RIGHT_NEEDS_USERS_GET';
export const ITEMS_PREFIX = 'ROLE_RIGHT_ITEMS';
export const RIGHT_ITEMS_GET = 'ROLE_RIGHT_ITEMS_GET';
export const RIGHT_ITEMS_POST = 'ROLE_RIGHT_ITEMS_POST';
export const RIGHT_ITEMS_PUT = 'ROLE_RIGHT_ITEMS_PUT';
export const RIGHT_ITEMS_PATCH = 'ROLE_RIGHT_ITEMS_PATCH';
export const RIGHT_ITEMS_PATCH_BROKEN = 'ROLE_RIGHT_ITEMS_PATCH_BROKEN';
export const RIGHT_ITEMS_PATCH_SLOT = 'ROLE_RIGHT_ITEMS_PATCH_SLOT';
export const RIGHT_ITEMS_PATCH_QUANTITY = 'ROLE_RIGHT_ITEMS_PATCH_QUANTITY';
export const RIGHT_ITEMS_DELETE = 'ROLE_RIGHT_ITEMS_DELETE';
export const RIGHT_ITEMS_GET_FOREIGN_PROJECT = 'ROLE_RIGHT_ITEMS_GET_FOREIGN_PROJECT';
export const ITEMS_NOTES_PREFIX = 'ROLE_RIGHT_ITEMS_NOTES';
export const RIGHT_ITEMS_NOTES_GET = 'ROLE_RIGHT_ITEMS_NOTES_GET';
export const RIGHT_ITEMS_NOTES_POST = 'ROLE_RIGHT_ITEMS_NOTES_POST';
export const RIGHT_ITEMS_NOTES_DELETE = 'ROLE_RIGHT_ITEMS_NOTES_DELETE';
export const RIGHT_ITEMS_NOTES_DELETE_FOREIGN = 'ROLE_RIGHT_ITEMS_NOTES_DELETE_FOREIGN';
export const ITEM_TAGS_PREFIX = 'ROLE_RIGHT_ITEM_TAGS';
export const RIGHT_ITEM_TAGS_GET = 'ROLE_RIGHT_ITEM_TAGS_GET';
export const RIGHT_ITEM_TAGS_POST = 'ROLE_RIGHT_ITEM_TAGS_POST';
export const RIGHT_ITEM_TAGS_DELETE = 'ROLE_RIGHT_ITEM_TAGS_DELETE';
export const ITEMS_ITEM_TAGS_PREFIX = 'ROLE_RIGHT_ITEMS_ITEM_TAGS';
export const RIGHT_ITEMS_ITEM_TAGS_GET = 'ROLE_RIGHT_ITEMS_ITEM_TAGS_GET';
export const RIGHT_ITEMS_ITEM_TAGS_POST = 'ROLE_RIGHT_ITEMS_ITEM_TAGS_POST';
export const RIGHT_ITEMS_ITEM_TAGS_DELETE = 'ROLE_RIGHT_ITEMS_ITEM_TAGS_DELETE';
export const SLOTS_PREFIX = 'ROLE_RIGHT_SLOTS';
export const RIGHT_SLOTS_GET = 'ROLE_RIGHT_SLOTS_GET';
export const RIGHT_SLOTS_POST = 'ROLE_RIGHT_SLOTS_POST';
export const RIGHT_SLOTS_PUT = 'ROLE_RIGHT_SLOTS_PUT';
export const RIGHT_SLOTS_DELETE = 'ROLE_RIGHT_SLOTS_DELETE';
export const STORES_PREFIX = 'ROLE_RIGHT_STORES';
export const RIGHT_STORES_GET = 'ROLE_RIGHT_STORES_GET';
export const RIGHT_STORES_POST = 'ROLE_RIGHT_STORES_POST';
export const RIGHT_STORES_PUT = 'ROLE_RIGHT_STORES_PUT';
export const RIGHT_STORES_DELETE = 'ROLE_RIGHT_STORES_DELETE';
export const RIGHT_STORES_GET_FOREIGN_PROJECT = 'ROLE_RIGHT_STORES_GET_FOREIGN_PROJECT';
export const TECHNICAL_CREWS_PREFIX = 'ROLE_RIGHT_TECHNICAL_CREWS';
export const RIGHT_TECHNICAL_CREWS_GET = 'ROLE_RIGHT_TECHNICAL_CREWS_GET';


