// Needs to be kept in sync with UserRole.java

//  ██████╗__██████╗_██╗_____███████╗███████╗
//  ██╔══██╗██╔═══██╗██║_____██╔════╝██╔════╝
//  ██████╔╝██║___██║██║_____█████╗__███████╗
//  ██╔══██╗██║___██║██║_____██╔══╝__╚════██║
//  ██║__██║╚██████╔╝███████╗███████╗███████║
//  ╚═╝__╚═╝_╚═════╝_╚══════╝╚══════╝╚══════╝

export const ROLE_ADMIN = 'ROLE_ADMIN';
export const ROLE_CONSTRUCTION_SERVANT = 'ROLE_CONSTRUCTION_SERVANT';
export const ROLE_LOCAL_COORDINATOR = 'ROLE_LOCAL_COORDINATOR';
// needs to be able to check who will come to the construction site
export const ROLE_ATTENDANCE = 'ROLE_ATTENDANCE';
export const ROLE_PUBLISHER = 'ROLE_PUBLISHER';
export const ROLE_STORE_KEEPER = 'ROLE_STORE_KEEPER';
export const ROLE_INVENTORY_MANAGER = 'ROLE_INVENTORY_MANAGER';

//  ██████╗_██╗_██████╗_██╗__██╗████████╗███████╗
//  ██╔══██╗██║██╔════╝_██║__██║╚══██╔══╝██╔════╝
//  ██████╔╝██║██║__███╗███████║___██║___███████╗
//  ██╔══██╗██║██║___██║██╔══██║___██║___╚════██║
//  ██║__██║██║╚██████╔╝██║__██║___██║___███████║
//  ╚═╝__╚═╝╚═╝_╚═════╝_╚═╝__╚═╝___╚═╝___╚══════╝	

export const GET_SUFFIX = '_GET';
export const POST_SUFFIX = '_POST';
export const PUT_SUFFIX = '_PUT';
export const DELETE_SUFFIX = '_DELETE';

export const USERS_PREFIX = 'ROLE_RIGHT_USERS';
export const RIGHT_USERS_GET = USERS_PREFIX + GET_SUFFIX;
export const RIGHT_USERS_POST = USERS_PREFIX + POST_SUFFIX;
export const RIGHT_USERS_PUT = USERS_PREFIX + PUT_SUFFIX;
export const RIGHT_USERS_DELETE = USERS_PREFIX + DELETE_SUFFIX;
export const RIGHT_USERS_CHANGE_FOREIGN = USERS_PREFIX + '_CHANGE_FOREIGN';
export const RIGHT_USERS_CHANGE_FOREIGN_PASSWORD = USERS_PREFIX + '_CHANGE_FOREIGN_PASSWORD';
export const RIGHT_USERS_CHANGE_ROLES = USERS_PREFIX + '_CHANGE_ROLES';

export const USERS_ROLES_PREFIX = 'ROLE_RIGHT_USERS_ROLES';
export const RIGHT_USERS_ROLES_GET = USERS_ROLES_PREFIX + GET_SUFFIX;
export const RIGHT_USERS_ROLES_GET_FOREIGN = RIGHT_USERS_ROLES_GET + '_FOREIGN';
export const RIGHT_USERS_ROLES_POST = USERS_ROLES_PREFIX + POST_SUFFIX;
export const RIGHT_USERS_ROLES_DELETE = USERS_ROLES_PREFIX + DELETE_SUFFIX;

export const USERS_GRANT_ROLE_PREFIX = 'ROLE_RIGHT_USERS_GRANT';
export const RIGHT_USERS_GRANT_ROLE_ADMIN = USERS_GRANT_ROLE_PREFIX + '_' + ROLE_ADMIN;
export const RIGHT_USERS_GRANT_ROLE_CONSTRUCTION_SERVANT = USERS_GRANT_ROLE_PREFIX + '_'
    + ROLE_CONSTRUCTION_SERVANT;
export const RIGHT_USERS_GRANT_ROLE_LOCAL_COORDINATOR = USERS_GRANT_ROLE_PREFIX + '_'
    + ROLE_LOCAL_COORDINATOR;
export const RIGHT_USERS_GRANT_ROLE_ATTENDANCE = USERS_GRANT_ROLE_PREFIX + '_' + ROLE_ATTENDANCE;
export const RIGHT_USERS_GRANT_ROLE_PUBLISHER = USERS_GRANT_ROLE_PREFIX + '_' + ROLE_PUBLISHER;
export const RIGHT_USERS_GRANT_ROLE_STORE_KEEPER = USERS_GRANT_ROLE_PREFIX + '_' + ROLE_STORE_KEEPER;
export const RIGHT_USERS_GRANT_ROLE_INVENTORY_MANAGER = USERS_GRANT_ROLE_PREFIX + '_'
    + ROLE_INVENTORY_MANAGER;

export const PROJECTS_PREFIX = 'ROLE_RIGHT_PROJECTS';
export const RIGHT_PROJECTS_GET = PROJECTS_PREFIX + GET_SUFFIX;
export const RIGHT_PROJECTS_POST = PROJECTS_PREFIX + POST_SUFFIX;
export const RIGHT_PROJECTS_PUT = PROJECTS_PREFIX + PUT_SUFFIX;
export const RIGHT_PROJECTS_DELETE = PROJECTS_PREFIX + DELETE_SUFFIX;
export const RIGHT_PROJECTS_CHANGE_FOREIGN = PROJECTS_PREFIX + '_CHANGE_FOREIGN';

export const PROJECTS_USERS_PREFIX = 'ROLE_RIGHT_PROJECTS_USERS';
export const RIGHT_PROJECTS_USERS_GET = PROJECTS_USERS_PREFIX + GET_SUFFIX;
export const RIGHT_PROJECTS_USERS_POST = PROJECTS_USERS_PREFIX + POST_SUFFIX;
export const RIGHT_PROJECTS_USERS_DELETE = PROJECTS_USERS_PREFIX + DELETE_SUFFIX;
export const RIGHT_PROJECTS_USERS_CHANGE_FOREIGN = PROJECTS_USERS_PREFIX + '_CHANGE_FOREIGN';

export const PROJECTS_HELPER_TYPES_PREFIX = 'ROLE_RIGHT_PROJECTS_HELPER_TYPES';
export const RIGHT_PROJECTS_HELPER_TYPES_GET = PROJECTS_HELPER_TYPES_PREFIX + GET_SUFFIX;
export const RIGHT_PROJECTS_HELPER_TYPES_POST = PROJECTS_HELPER_TYPES_PREFIX + POST_SUFFIX;
export const RIGHT_PROJECTS_HELPER_TYPES_PUT = PROJECTS_HELPER_TYPES_PREFIX + PUT_SUFFIX;
export const RIGHT_PROJECTS_HELPER_TYPES_DELETE = PROJECTS_HELPER_TYPES_PREFIX + DELETE_SUFFIX;

export const HELPER_TYPES_PREFIX = 'ROLE_RIGHT_HELPER_TYPES';
export const RIGHT_HELPER_TYPES_GET = HELPER_TYPES_PREFIX + GET_SUFFIX;
export const RIGHT_HELPER_TYPES_POST = HELPER_TYPES_PREFIX + POST_SUFFIX;
export const RIGHT_HELPER_TYPES_PUT = HELPER_TYPES_PREFIX + PUT_SUFFIX;
export const RIGHT_HELPER_TYPES_DELETE = HELPER_TYPES_PREFIX + DELETE_SUFFIX;

export const NEEDS_PREFIX = 'ROLE_RIGHT_NEEDS';
export const RIGHT_NEEDS_GET = NEEDS_PREFIX + GET_SUFFIX;
export const RIGHT_NEEDS_POST = NEEDS_PREFIX + POST_SUFFIX;
export const RIGHT_NEEDS_PUT = NEEDS_PREFIX + PUT_SUFFIX;
export const RIGHT_NEEDS_DELETE = NEEDS_PREFIX + DELETE_SUFFIX;
export const RIGHT_NEEDS_CHANGE_FOREIGN_PROJECT = NEEDS_PREFIX + '_CHANGE_FOREIGN_PROJECT';
export const RIGHT_NEEDS_CHANGE_FOREIGN_USER = NEEDS_PREFIX + '_CHANGE_FOREIGN_USER';
export const RIGHT_NEEDS_GET_FOREIGN_USER = NEEDS_PREFIX + GET_SUFFIX + '_FOREIGN_USER';
export const RIGHT_NEEDS_GET_ANONYMIZED_USER_LIST = NEEDS_PREFIX + GET_SUFFIX
    + '_ANONYMIZED_USER_LIST';
export const RIGHT_NEEDS_APPLY = NEEDS_PREFIX + '_APPLY';
export const RIGHT_NEEDS_APPROVE = NEEDS_PREFIX + '_APPROVE';
export const RIGHT_NEEDS_VIEW_APPROVED = NEEDS_PREFIX + '_VIEW_APPROVED';

export const NEEDS_USERS_PREFIX = 'ROLE_RIGHT_NEEDS_USERS';
export const RIGHT_NEEDS_USERS_PUT = NEEDS_USERS_PREFIX + PUT_SUFFIX;
export const RIGHT_NEEDS_USERS_GET = NEEDS_USERS_PREFIX + GET_SUFFIX;

export const ITEMS_PREFIX = 'ROLE_RIGHT_ITEMS';
export const RIGHT_ITEMS_GET = ITEMS_PREFIX + GET_SUFFIX;
export const RIGHT_ITEMS_POST = ITEMS_PREFIX + POST_SUFFIX;
export const RIGHT_ITEMS_PUT = ITEMS_PREFIX + PUT_SUFFIX;
export const RIGHT_ITEMS_PATCH = ITEMS_PREFIX + '_PATCH';
export const RIGHT_ITEMS_PATCH_BROKEN = RIGHT_ITEMS_PATCH + '_BROKEN';
export const RIGHT_ITEMS_PATCH_SLOT = RIGHT_ITEMS_PATCH + '_SLOT';
export const RIGHT_ITEMS_PATCH_QUANTITY = RIGHT_ITEMS_PATCH + '_QUANTITY';
export const RIGHT_ITEMS_DELETE = ITEMS_PREFIX + DELETE_SUFFIX;
export const RIGHT_ITEMS_GET_FOREIGN_PROJECT = RIGHT_ITEMS_GET + '_FOREIGN_PROJECT';

export const ITEMS_NOTES_PREFIX = 'ROLE_RIGHT_ITEMS_NOTES';
export const RIGHT_ITEMS_NOTES_GET = ITEMS_NOTES_PREFIX + GET_SUFFIX;
export const RIGHT_ITEMS_NOTES_POST = ITEMS_NOTES_PREFIX + POST_SUFFIX;
export const RIGHT_ITEMS_NOTES_DELETE = ITEMS_NOTES_PREFIX + DELETE_SUFFIX;
export const RIGHT_ITEMS_NOTES_DELETE_FOREIGN = RIGHT_ITEMS_NOTES_DELETE + '_FOREIGN';

export const ITEM_TAGS_PREFIX = 'ROLE_RIGHT_ITEM_TAGS';
export const RIGHT_ITEM_TAGS_GET = ITEM_TAGS_PREFIX + GET_SUFFIX;
export const RIGHT_ITEM_TAGS_POST = ITEM_TAGS_PREFIX + POST_SUFFIX;
export const RIGHT_ITEM_TAGS_DELETE = ITEM_TAGS_PREFIX + DELETE_SUFFIX;

export const ITEMS_ITEM_TAGS_PREFIX = 'ROLE_RIGHT_ITEMS_ITEM_TAGS';
export const RIGHT_ITEMS_ITEM_TAGS_GET = ITEMS_ITEM_TAGS_PREFIX + GET_SUFFIX;
export const RIGHT_ITEMS_ITEM_TAGS_POST = ITEMS_ITEM_TAGS_PREFIX + POST_SUFFIX;
export const RIGHT_ITEMS_ITEM_TAGS_DELETE = ITEMS_ITEM_TAGS_PREFIX + DELETE_SUFFIX;

export const SLOTS_PREFIX = 'ROLE_RIGHT_SLOTS';
export const RIGHT_SLOTS_GET = SLOTS_PREFIX + GET_SUFFIX;
export const RIGHT_SLOTS_POST = SLOTS_PREFIX + POST_SUFFIX;
export const RIGHT_SLOTS_PUT = SLOTS_PREFIX + PUT_SUFFIX;
export const RIGHT_SLOTS_DELETE = SLOTS_PREFIX + DELETE_SUFFIX;

export const STORES_PREFIX = 'ROLE_RIGHT_STORES';
export const RIGHT_STORES_GET = STORES_PREFIX + GET_SUFFIX;
export const RIGHT_STORES_POST = STORES_PREFIX + POST_SUFFIX;
export const RIGHT_STORES_PUT = STORES_PREFIX + PUT_SUFFIX;
export const RIGHT_STORES_DELETE = STORES_PREFIX + DELETE_SUFFIX;
export const RIGHT_STORES_GET_FOREIGN_PROJECT = RIGHT_STORES_GET + '_FOREIGN_PROJECT';

export const TECHNICAL_CREWS_PREFIX = 'ROLE_RIGHT_TECHNICAL_CREWS';
export const RIGHT_TECHNICAL_CREWS_GET = TECHNICAL_CREWS_PREFIX + GET_SUFFIX;



