# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Continious Integration

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Verify
      run: mvn verify
      
    - ńame: Deploy
      if: ${{ success() && (github.ref_name == 'stage' || github.ref_name == 'prod') }}
      run: scripts/deploy.sh $GITHUB_REF_NAME
      env: 
        CREDENTIALS_DB_PW: ${{ secrets.CREDENTIALS_DB_PW}}
        CREDENTIALS_DB_USERNAME: ${{ secrets.CREDENTIALS_DB_USERNAME}}
        CREDENTIALS_JWT_EXPIRATION: ${{ secrets.CREDENTIALS_JWT_EXPIRATION}}
        CREDENTIALS_PROD_BASE: ${{ secrets.CREDENTIALS_PROD_BASE}}
        CREDENTIALS_PROD_DB_URL: ${{ secrets.CREDENTIALS_PROD_DB_URL}}
        CREDENTIALS_PROD_JWT_SECRET: ${{ secrets.CREDENTIALS_PROD_JWT_SECRET}}
        CREDENTIALS_SMTP_HOST: ${{ secrets.CREDENTIALS_SMTP_HOST}}
        CREDENTIALS_SMTP_PW: ${{ secrets.CREDENTIALS_SMTP_PW}}
        CREDENTIALS_SMTP_USER: ${{ secrets.CREDENTIALS_SMTP_USER}}
        CREDENTIALS_STAGE_BASE: ${{ secrets.CREDENTIALS_STAGE_BASE}}
        CREDENTIALS_STAGE_DB_URL: ${{ secrets.CREDENTIALS_STAGE_DB_URL}}
        CREDENTIALS_STAGE_JWT_SECRET: ${{ secrets.CREDENTIALS_STAGE_JWT_SECRET}}
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST}}
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY}}
        DEPLOY_PORT: ${{ secrets.DEPLOY_PORT}}
        DEPLOY_PW: ${{ secrets.DEPLOY_PW}}
        DEPLOY_TARGET: ${{ secrets.DEPLOY_TARGET}}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER}}
        DEPLOY_WAR_PATH : ${{ secrets.DEPLOY_WAR_PATH}}
    
  # TODO use maven to run sonar
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
